### ISSUE TITLE
Error when digging grass block.

### ISSUE THREAD

**Issue by Tim79000** [MadKamel/ksurvive-revival#10]
AsyncErr: Lua: Runtime error from mod 'ks_terrain' in callback node_on_dig(): Unknown node: ks_terrain:silty_soil
stack traceback:
	[C]: in function '__index'
	...Custom\Desktop\Minetest\bin\..\builtin\common\item_s.lua:229: in function <...Custom\Desktop\Minetest\bin\..\builtin\common\item_s.lua:228>
	[C]: in function 'set_node'
	...inetest\bin\..\games\ksurvive2\mods\ks_terrain/nodes.lua:50: in function 'after_dig_node'
	...ers\Custom\Desktop\Minetest\bin\..\builtin\game\item.lua:547: in function <...ers\Custom\Desktop\Minetest\bin\..\builtin\game\item.lua:460>

I know, it's trying to replace the block with the same fashion of blueberry bushes from MTG or holly tree leaves, but silty soil got replaced.

**Comment by MadKamel** [comment]
Oh, that's strange. I thought I had a node called silty soil. I'll check and see what's wrong.

**Comment by MadKamel** [comment]
Okay, turns out the node was called 'ks_terrain:silt_soil', not silty soil. Fixed.
