### ISSUE TITLE
Creative Commons 0 Sounds

### ISSUE THREAD

**Issue by Tim79000** [MadKamel/ksurvive-revival#12]
https://github.com/jordan4ibanez/Crafter/tree/master/mods/main/sounds
Read the attributions file, these are some great sounds until you can make them yourself by breaking bricks with you garage-mattock.

**Comment by MadKamel** [comment]
Awesome! Thanks for linking this, and I think I'll give some a whirl to see if I can use them as placeholders.

**Comment by Tim79000** [comment]
Brilliant.
