### ISSUE TITLE
Make pitch have better contrast, if it even has some.

### ISSUE THREAD

**Issue by Tim79000** [MadKamel/ksurvive-revival#8]
It's just pitch black, is this intended?

**Comment by MadKamel** [comment]
Yeah, it was supposed to be pitch black with minute, dark details. The details are very dark on purpose. I will consider increasing the visibility of pitch, however. It is a very dangerous substance, so the player would likely need some kind of way to see pitch better.

**Comment by MadKamel** [comment]
I think that pitch is dark enough that it should alert a player if they see it. I think this issue isn't big enough to justify editing the pitch textures.
